name: my first github action
on: [push, repository_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
        image: fredoo404/build
    steps:
        - name: Fix
          run: sudo chown -R circleci /__w && sudo chmod -R 777 /__w
        - uses: actions/checkout@master
        - name: Test ls 1
          run: ls -l 
        - name: Hello world
          run: python ./main.py
          env: 
            MY_SECRET_ENV: ${{ secrets.MY_SECRET_ENV }}
            secret: ${{ secrets.MY_SECRET_ENV }}