name: my first github action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
        image: fredoo404/build
    steps:
        - uses: actions/checkout@master
        - name: Test ls 1
          run: ls -l 
        - name: Hello world
          run: python ./main.py
          with:
              entrypoint: sudo chown -R circleci /github && chmod -R 777 /github