name: my first github action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
        image: fredoo404/build
    volumes:
        - /home/runner:/test
    steps:
        - name: Test ls 1
          run: ls -l /test
        - name: Hello world
          run: python main.py