name: my first github action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
        image: fredoo404/build
    steps:
        - name: Test ls 1
          run: ls -l /github/home/
        - name: Hello world
          run: python main.py